---
version: "3.8"

# Common to all services
x-common: &common
  restart: unless-stopped
  environment: &common-environment
    CERT_PUBLIC_KEY: |
      ${CERT_PUBLIC_KEY}
    CERT_PRIVATE_KEY: |
      ${CERT_PRIVATE_KEY}
    CERT_AUTHORITY: |
      ${CERT_AUTHORITY}

x-traefik-https-redirect-middleware: &traefik-https-redirect-middleware
  traefik.enable: true
  traefik.http.middlewares.https-redirect.redirectscheme.permanent: true
  traefik.http.middlewares.https-redirect.redirectscheme.scheme: https

x-traefik-https-redirect: &traefik-https-redirect https-redirect

volumes:
  activemq-data: {}
  blazegraph-data: {}
  cantaloupe-data: {}
  drupal-private-files: {}
  drupal-public-files: {}
  fcrepo-data: {}
  mariadb-data: {}
  matomo-config-data: {}
  solr-data: {}

services:
  activemq:
    <<: *common
    container_name: activemq
    image: ${ISLE_BUILDKIT_REPOSITORY}/activemq:${ISLE_BUILDKIT_TAG}
    labels:
      <<: *traefik-https-redirect-middleware
      traefik.http.routers.activemq_http.entrypoints: http
      traefik.http.routers.activemq_http.middlewares: *traefik-https-redirect
      traefik.http.routers.activemq_http.rule: &traefik-host-activemq Host(`activemq.islandora.dev`)
      traefik.http.routers.activemq_http.service: activemq
      traefik.http.routers.activemq_https.entrypoints: https
      traefik.http.routers.activemq_https.rule: *traefik-host-activemq
      traefik.http.routers.activemq_https.tls: true
      traefik.http.services.activemq.loadbalancer.server.port: 8161
    volumes:
      - activemq-data:/opt/activemq/data:rw
  alpaca:
    <<: *common
    container_name: alpaca
    image: ${ISLE_BUILDKIT_REPOSITORY}/alpaca:${ISLE_BUILDKIT_TAG}
    environment:
      <<: *common-environment
      ALPACA_ACTIVEMQ_CONNECTIONS: 20
      ALPACA_ACTIVEMQ_CONSUMERS: 8
  blazegraph:
    <<: *common
    container_name: blazegraph
    image: ${ISLE_BUILDKIT_REPOSITORY}/blazegraph:${ISLE_BUILDKIT_TAG}
    labels:
      <<: *traefik-https-redirect-middleware
      traefik.http.routers.blazegraph_http.entrypoints: http
      traefik.http.routers.blazegraph_http.middlewares: *traefik-https-redirect
      traefik.http.routers.blazegraph_http.service: blazegraph
      traefik.http.routers.blazegraph_https.entrypoints: https
      traefik.http.routers.blazegraph_https.tls: true
      traefik.http.services.blazegraph.loadbalancer.server.port: 8080
    volumes:
      - blazegraph-data:/data:rw
  cantaloupe:
    <<: *common
    container_name: cantaloupe
    image: ${ISLE_BUILDKIT_REPOSITORY}/cantaloupe:${ISLE_BUILDKIT_TAG}
    labels:
      <<: *traefik-https-redirect-middleware
      traefik.http.routers.cantaloupe_http.entrypoints: http
      traefik.http.routers.cantaloupe_http.middlewares: *traefik-https-redirect
      traefik.http.routers.cantaloupe_http.rule: &traefik-host-cantaloupe Host(`sandbox.islandora.dev`) && PathPrefix(`/cantaloupe`)
      traefik.http.routers.cantaloupe_http.service: cantaloupe
      traefik.http.routers.cantaloupe_https.entrypoints: https
      traefik.http.routers.cantaloupe_https.rule: *traefik-host-cantaloupe
      traefik.http.routers.cantaloupe_https.tls: true
      traefik.http.services.cantaloupe.loadbalancer.server.port: 8080
    volumes:
      - cantaloupe-data:/data:rw
  crayfits:
    <<: *common
    container_name: crayfits
    image: ${ISLE_BUILDKIT_REPOSITORY}/crayfits:${ISLE_BUILDKIT_TAG}
  drupal:
    <<: *common
    container_name: drupal
    image: ${REPOSITORY}/sandbox-drupal:${TAG}
    labels:
      <<: *traefik-https-redirect-middleware
      traefik.http.routers.drupal_http.entrypoints: http
      traefik.http.routers.drupal_http.middlewares: *traefik-https-redirect
      traefik.http.routers.drupal_http.rule: &traefik-host-drupal Host(`sandbox.islandora.dev`)
      traefik.http.routers.drupal_http.service: drupal
      traefik.http.routers.drupal_https.entrypoints: https
      traefik.http.routers.drupal_https.rule: *traefik-host-drupal
      traefik.http.routers.drupal_https.service: drupal
      traefik.http.routers.drupal_https.tls: true
      traefik.http.services.drupal.loadbalancer.server.port: 80
    environment:
      <<: *common-environment
      DRUPAL_DEFAULT_ACCOUNT_EMAIL: "community@islandora.ca"
      DRUPAL_DEFAULT_ACCOUNT_PASSWORD: ${DRUPAL_DEFAULT_ACCOUNT_PASSWORD}
      DRUPAL_DEFAULT_BROKER_URL: "tcp://activemq:61613"
      DRUPAL_DEFAULT_CANTALOUPE_URL: "https://sandbox.islandora.dev/cantaloupe/iiif/2"
      DRUPAL_DEFAULT_CONFIGDIR: "/var/www/drupal/config/sync"
      DRUPAL_DEFAULT_FCREPO_HOST: "fcrepo"
      DRUPAL_DEFAULT_FCREPO_PORT: 8080
      DRUPAL_DEFAULT_FCREPO_URL: "https://fcrepo.islandora.dev/fcrepo/rest/"
      DRUPAL_DEFAULT_INSTALL_EXISTING_CONFIG: "true"
      DRUPAL_DEFAULT_MATOMO_URL: "https://sandbox.islandora.dev/matomo/"
      DRUPAL_DEFAULT_NAME: "Islandora Digital Collections"
      DRUPAL_DEFAULT_PROFILE: "islandora_install_profile_demo"
      DRUPAL_DEFAULT_SALT: ${DRUPAL_DEFAULT_SALT}
      DRUPAL_DEFAULT_SITE_URL: "sandbox.islandora.dev"
      DRUPAL_DEFAULT_SOLR_CORE: "default"
      DRUPAL_DRUSH_URI: "https://sandbox.islandora.dev"
    volumes:
      - drupal-public-files:/var/www/drupal/web/sites/default/files
      - drupal-private-files:/var/www/drupal/private
    depends_on:
      - activemq
      - blazegraph
      - fcrepo
      - mariadb
      - solr
  fits:
    <<: *common
    container_name: fits
    image: ${ISLE_BUILDKIT_REPOSITORY}/fits:${ISLE_BUILDKIT_TAG}
  homarus:
    <<: *common
    container_name: homarus
    image: ${ISLE_BUILDKIT_REPOSITORY}/homarus:${ISLE_BUILDKIT_TAG}
  houdini:
    <<: *common
    container_name: houdini
    image: ${ISLE_BUILDKIT_REPOSITORY}/houdini:${ISLE_BUILDKIT_TAG}
  hypercube:
    <<: *common
    container_name: hypercube
    image: ${ISLE_BUILDKIT_REPOSITORY}/hypercube:${ISLE_BUILDKIT_TAG}
  mariadb:
    <<: *common
    container_name: mariadb
    image: ${ISLE_BUILDKIT_REPOSITORY}/mariadb:${ISLE_BUILDKIT_TAG}
    volumes:
      - mariadb-data:/var/lib/mysql:rw
  milliner:
    <<: *common
    container_name: milliner
    image: ${ISLE_BUILDKIT_REPOSITORY}/milliner:${ISLE_BUILDKIT_TAG}
  fcrepo:
    <<: *common
    container_name: fcrepo
    image: ${ISLE_BUILDKIT_REPOSITORY}/fcrepo6:${ISLE_BUILDKIT_TAG}
    environment:
      <<: *common-environment
      FCREPO_ALLOW_EXTERNAL_DEFAULT: "http://default/"
      FCREPO_ALLOW_EXTERNAL_SANDBOX: "http://sandbox.islandora.dev/"
      FCREPO_ALLOW_EXTERNAL_SANDBOX_HTTPS: "https://sandbox.islandora.dev/"
    labels:
      <<: *traefik-https-redirect-middleware
      # Due to weird logic in `fcrepo/static/js/common.js`, do not use https
      # as it assumes it always needs to append /fcr:metadata to every request
      # breaking the links. Though for files we do want that page to be accessed
      # so check for a file extension.
      traefik.http.middlewares.fcrepo-strip-suffix.replacepathregex.regex: "^(.*/fcrepo/rest/[^.]*)/fcr:metadata$$"
      traefik.http.middlewares.fcrepo-strip-suffix.replacepathregex.replacement: "$$1"
      traefik.http.routers.fcrepo_http.entrypoints: http
      traefik.http.routers.fcrepo_http.middlewares: *traefik-https-redirect
      traefik.http.routers.fcrepo_http.service: fcrepo
      traefik.http.routers.fcrepo_https.entrypoints: https
      traefik.http.routers.fcrepo_https.middlewares: fcrepo-strip-suffix
      traefik.http.routers.fcrepo_https.tls: true
      traefik.http.services.fcrepo.loadbalancer.server.port: 8080
    volumes:
      - fcrepo-data:/data
    depends_on:
      - activemq
  matomo:
    <<: *common
    container_name: matomo
    image: ${ISLE_BUILDKIT_REPOSITORY}/matomo:${ISLE_BUILDKIT_TAG}
    labels:
      <<: *traefik-https-redirect-middleware
      traefik.http.middlewares.matomo-customrequestheaders.headers.customrequestheaders.X-Forwarded-Uri: /matomo
      traefik.http.middlewares.matomo-stripprefix.stripprefix.prefixes: /matomo
      traefik.http.middlewares.matomo.chain.middlewares: matomo-stripprefix,matomo-customrequestheaders
      traefik.http.routers.matomo_http.entrypoints: http
      traefik.http.routers.matomo_http.middlewares: *traefik-https-redirect
      traefik.http.routers.matomo_http.rule: &traefik-host-matomo Host(`sandbox.islandora.dev`) && PathPrefix(`/matomo`)
      traefik.http.routers.matomo_http.service: matomo
      traefik.http.routers.matomo_https.entrypoints: https
      traefik.http.routers.matomo_https.middlewares: matomo
      traefik.http.routers.matomo_https.rule: *traefik-host-matomo
      traefik.http.routers.matomo_https.tls: true
      traefik.http.services.matomo.loadbalancer.server.port: 80
    environment:
      <<: *common-environment
      MATOMO_DEFAULT_HOST: "https://sandbox.islandora.dev"
    volumes:
      - matomo-config-data:/var/www/matomo:rw
  solr:
    <<: *common
    container_name: solr
    image: ${REPOSITORY}/sandbox-solr:${TAG}
    labels:
      <<: *traefik-https-redirect-middleware
      traefik.http.routers.solr_http.entrypoints: http
      traefik.http.routers.solr_http.middlewares: *traefik-https-redirect
      traefik.http.routers.solr_http.service: solr
      traefik.http.routers.solr_https.entrypoints: https
      traefik.http.routers.solr_https.tls: true
      traefik.http.services.solr.loadbalancer.server.port: 8983
    networks:
      default:
        aliases:
          - solr.islandora.dev
    volumes:
      - solr-data:/data:rw
  traefik:
    <<: *common
    container_name: traefik
    image: ${REPOSITORY}/sandbox-traefik:${TAG}
    command: >-
      --api.insecure=true
      --api.dashboard=true
      --api.debug=true
      --entryPoints.http.address=:80
      --entryPoints.https.address=:443
      --providers.file.filename=/etc/traefik/tls.yml
      --providers.docker=true
      --providers.docker.network=default
      --providers.docker.exposedByDefault=false
      '--providers.docker.defaultRule=Host(`{{index .Labels "com.docker.compose.service" }}.islandora.dev`)'
    labels:
      <<: *traefik-https-redirect-middleware
      traefik.http.routers.traefik_http.entrypoints: http
      traefik.http.routers.traefik_http.middlewares: *traefik-https-redirect
      traefik.http.routers.traefik_http.service: traefik
      traefik.http.routers.traefik_https.entrypoints: https
      traefik.http.routers.traefik_https.tls: true
      traefik.http.services.traefik.loadbalancer.server.port: 8080
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      default:
        # Allow derivative services to connect to the drupal service via https.
        aliases:
          - sandbox.islandora.dev
          - fcrepo.islandora.dev