---
version: "3.8"

# Common to all services
x-common: &common
    restart: unless-stopped
    tty: true # Required for non-root users with selinux enabled.

x-password: &password "7mNWe6Gp8wH71SFXD6GZAJmlx2z68315BLaUPzX5DRkp248t"

x-traefik-https-redirect-middleware: &traefik-https-redirect-middleware
  traefik.enable: true
  traefik.http.middlewares.https-redirect.redirectscheme.permanent: true
  traefik.http.middlewares.https-redirect.redirectscheme.scheme: https

x-traefik-https-redirect: &traefik-https-redirect https-redirect

networks:
    default:

volumes:
    drupal-solr-config: {}

services:
    alpaca:
        <<: *common
        image: ${ISLANDORA_REPOSITORY}/alpaca:${ISLANDORA_TAG}
    crayfits:
        <<: *common
        image: ${ISLANDORA_REPOSITORY}/crayfits:${ISLANDORA_TAG}
    fits:
        <<: *common
        image: ${ISLANDORA_REPOSITORY}/fits:${ISLANDORA_TAG}
    homarus:
        <<: *common
        image: ${ISLANDORA_REPOSITORY}/homarus:${ISLANDORA_TAG}
    houdini:
        <<: *common
        image: ${ISLANDORA_REPOSITORY}/houdini:${ISLANDORA_TAG}
    hypercube:
        <<: *common
        image: ${ISLANDORA_REPOSITORY}/hypercube:${ISLANDORA_TAG}
    mariadb:
        <<: *common
        image: ${ISLANDORA_REPOSITORY}/mariadb:${ISLANDORA_TAG}
    milliner:
        <<: *common
        image: ${ISLANDORA_REPOSITORY}/milliner:${ISLANDORA_TAG}
    activemq:
        <<: *common
        image: ${ISLANDORA_REPOSITORY}/activemq:${ISLANDORA_TAG}
        labels:
          <<: *traefik-https-redirect-middleware
          traefik.http.routers.activemq_http.entrypoints: http
          traefik.http.routers.activemq_http.middlewares: *traefik-https-redirect
          traefik.http.routers.activemq_http.rule: &traefik-host-activemq Host(`activemq.${DOMAIN}`)
          traefik.http.routers.activemq_http.service: activemq
          traefik.http.routers.activemq_https.entrypoints: https
          traefik.http.routers.activemq_https.rule: *traefik-host-activemq
          traefik.http.services.activemq.loadbalancer.server.port: 8161
          traefik.subdomain: activemq
        environment:
          ACTIVEMQ_WEB_ADMIN_PASSWORD: *password
    blazegraph:
        <<: *common
        image: ${ISLANDORA_REPOSITORY}/blazegraph:${ISLANDORA_TAG}
        labels:
            <<: *traefik-https-redirect-middleware
            traefik.http.routers.blazegraph_http.entrypoints: http
            traefik.http.routers.blazegraph_http.middlewares: *traefik-https-redirect
            traefik.http.routers.blazegraph_http.rule: &traefik-host-drupal Host(`blazegraph.${DOMAIN}`)
            traefik.http.routers.blazegraph_http.service: blazegraph
            traefik.http.routers.blazegraph_https.entrypoints: https
            traefik.http.routers.blazegraph_https.rule: *traefik-host-drupal
            traefik.http.routers.blazegraph_https.service: blazegraph
            traefik.http.services.blazegraph.loadbalancer.server.port: 8080
    cantaloupe:
        <<: *common
        image: ${ISLANDORA_REPOSITORY}/cantaloupe:${ISLANDORA_TAG}
        labels:
            <<: *traefik-https-redirect-middleware
            traefik.http.middlewares.cantaloupe-custom-request-headers.headers.customrequestheaders.X-Forwarded-Path: /cantaloupe
            traefik.http.middlewares.cantaloupe-strip-prefix.stripprefix.prefixes: /cantaloupe
            traefik.http.middlewares.cantaloupe.chain.middlewares: cantaloupe-strip-prefix,cantaloupe-custom-request-headers
            traefik.http.routers.cantaloupe_http.entrypoints: http
            traefik.http.routers.cantaloupe_http.middlewares: *traefik-https-redirect
            traefik.http.routers.cantaloupe_http.rule: &traefik-host-cantaloupe Host(`${DOMAIN}`) && PathPrefix(`/cantaloupe`)
            traefik.http.routers.cantaloupe_http.service: cantaloupe
            traefik.http.routers.cantaloupe_https.middlewares: cantaloupe
            traefik.http.routers.cantaloupe_https.entrypoints: https
            traefik.http.routers.cantaloupe_https.rule: *traefik-host-cantaloupe
            traefik.http.services.cantaloupe.loadbalancer.server.port: 8182
    drupal:
        <<: *common
        image: ${REPOSITORY}/sandbox:${TAG}
        labels:
            <<: *traefik-https-redirect-middleware
            traefik.http.routers.drupal_http.entrypoints: http
            traefik.http.routers.drupal_http.middlewares: *traefik-https-redirect
            traefik.http.routers.drupal_http.rule: &traefik-host-drupal Host(`${DOMAIN}`)
            traefik.http.routers.drupal_http.service: drupal
            traefik.http.routers.drupal_https.entrypoints: https
            traefik.http.routers.drupal_https.rule: *traefik-host-drupal
            traefik.http.routers.drupal_https.service: drupal
            traefik.http.services.drupal.loadbalancer.server.port: 80
        environment:
            DRUPAL_ACTIVEMQ_WEB_ADMIN_PASSWORD: *password
            DRUPAL_DEFAULT_ACCOUNT_EMAIL: "community@islandora.ca"
            DRUPAL_DEFAULT_ACCOUNT_PASSWORD: *password
            DRUPAL_DEFAULT_BROKER_URL: "tcp://activemq:61613"
            DRUPAL_DEFAULT_CANTALOUPE_URL: "https://${DOMAIN}/cantaloupe/iiif/2"
            DRUPAL_DEFAULT_CONFIGDIR: "/var/www/drupal/config/sync"
            DRUPAL_DEFAULT_FCREPO_HOST: "fcrepo"
            DRUPAL_DEFAULT_FCREPO_PORT: 8080
            DRUPAL_DEFAULT_FCREPO_URL: "https://fcrepo.${DOMAIN}/fcrepo/rest/"
            DRUPAL_DEFAULT_INSTALL_EXISTING_CONFIG: "true"
            DRUPAL_DEFAULT_MATOMO_URL: "https://${DOMAIN}/matomo/"
            DRUPAL_DEFAULT_NAME: "Islandora Sandbox"
            DRUPAL_DEFAULT_PROFILE: "minimal"
            DRUPAL_DEFAULT_SITE_URL: "${DOMAIN}"
            DRUPAL_DEFAULT_SOLR_CORE: "default"
            DRUPAL_DRUSH_URI: "https://${DOMAIN}" # Used by docker/drupal/rootfs/usr/local/share/custom/install.sh
        volumes:
            - drupal-solr-config:/opt/solr/server/solr/default:ro
    fcrepo:
        <<: *common
        image: ${ISLANDORA_REPOSITORY}/fcrepo6:${ISLANDORA_TAG}
        environment:
            FCREPO_ALLOW_EXTERNAL_DEFAULT: "http://default/"
            FCREPO_ALLOW_EXTERNAL_DRUPAL: "https://${DOMAIN}/"
        labels:
            <<: *traefik-https-redirect-middleware
            # Due to weird logic in `fcrepo/static/js/common.js`, do not use https
            # as it assumes it always needs to append /fcr:metadata to every request
            # breaking the links. Though for files we do want that page to be accessed
            # so check for a file extension.
            traefik.http.middlewares.fcrepo-strip-suffix.replacepathregex.regex: "^(.*/fcrepo/rest/[^.]*)/fcr:metadata$$"
            traefik.http.middlewares.fcrepo-strip-suffix.replacepathregex.replacement: "$$1"
            traefik.http.routers.fcrepo_http.entrypoints: http
            traefik.http.routers.fcrepo_http.middlewares: *traefik-https-redirect
            traefik.http.routers.fcrepo_http.rule: &traefik-host-fcrepo Host(`fcrepo.${DOMAIN}`)
            traefik.http.routers.fcrepo_http.service: fcrepo
            traefik.http.routers.fcrepo_https.entrypoints: https
            traefik.http.routers.fcrepo_https.middlewares: fcrepo-strip-suffix
            traefik.http.routers.fcrepo_https.rule: *traefik-host-fcrepo
            traefik.http.services.fcrepo.loadbalancer.server.port: 8080
    matomo:
        <<: *common
        image: ${ISLANDORA_REPOSITORY}/matomo:${ISLANDORA_TAG}
        labels:
            traefik.enable: true
            traefik.http.middlewares.matomo-custom-request-headers.headers.customrequestheaders.X-Forwarded-Uri: /matomo
            traefik.http.middlewares.matomo-append-slash.redirectregex.regex: ^(https?://[^/]+/matomo)$$
            traefik.http.middlewares.matomo-append-slash.redirectregex.replacement: $${1}/
            traefik.http.middlewares.matomo-strip-prefix.stripprefix.prefixes: /matomo
            traefik.http.middlewares.matomo.chain.middlewares: matomo-append-slash,matomo-strip-prefix,matomo-custom-request-headers
            traefik.http.routers.matomo_http.entrypoints: http
            traefik.http.routers.matomo_http.middlewares: *traefik-https-redirect
            traefik.http.routers.matomo_http.rule: &traefik-host-matomo Host(`${DOMAIN}`) && PathPrefix(`/matomo`)
            traefik.http.routers.matomo_http.service: matomo
            traefik.http.routers.matomo_https.entrypoints: https
            traefik.http.routers.matomo_https.middlewares: matomo
            traefik.http.routers.matomo_https.rule: *traefik-host-matomo
            traefik.http.services.matomo.loadbalancer.server.port: 80
        environment:
            MATOMO_DEFAULT_HOST: "https://${DOMAIN}"
    solr:
        <<: *common
        image: ${ISLANDORA_REPOSITORY}/solr:${ISLANDORA_TAG}
        volumes:
            - type: volume
              source: drupal-solr-config
              target: /opt/solr/server/solr/default
              volume:
                  nocopy: true
    traefik:
        <<: *common
        image: traefik:v2.8.3
        # Change caServer to use the staging server when testing changes to the Traefik.
        #
        # Staging: https://acme-staging-v02.api.letsencrypt.org/directory
        # Production: https://acme-v02.api.letsencrypt.org/directory
        #
        # @See https://letsencrypt.org/docs/staging-environment/
        command: >-
          --api.insecure=false
          --api.dashboard=false
          --api.debug=false
          --entryPoints.http.address=:80
          --entryPoints.https.address=:443
          --entrypoints.https.http.tls.certResolver=resolver
          --entrypoints.https.http.tls.domains[0].main=sandbox.islandora.ca
          --entrypoints.https.http.tls.domains[0].sans=*.sandbox.islandora.ca
          --entrypoints.https.http.tls.domains[1].main=test.islandora.ca
          --entrypoints.https.http.tls.domains[1].sans=*.test.islandora.ca
          --providers.docker
          --providers.docker.network=default
          --providers.docker.exposedByDefault=false
          --certificatesresolvers.resolver.acme.httpchallenge=false
          --certificatesresolvers.resolver.acme.dnschallenge.provider=digitalocean
          --certificatesresolvers.resolver.acme.dnschallenge.delaybeforecheck=30
          --certificatesresolvers.resolver.acme.dnschallenge.resolvers=173.245.58.51:53,173.245.59.41:53,198.41.222.173:53
          --certificatesresolvers.resolver.acme.email=community@islandora.ca
          --certificatesresolvers.resolver.acme.storage=/acme/acme.json
          --certificatesResolvers.resolver.acme.caServer=https://acme-v02.api.letsencrypt.org/directory
        environment:
          DO_AUTH_TOKEN: "${DIGITALOCEAN_API_TOKEN}"
          DO_PROPAGATION_TIMEOUT: 300
        volumes:
          - /opt/sandbox/acme:/acme:Z
          - /var/run/docker.sock:/var/run/docker.sock:z
        ports:
            - "80:80"
            - "443:443"
        security_opt:
            - label=type:container_runtime_t # Required for selinux to access the docker socket.
        networks:
            default:
                aliases:
                    # Allow services to connect on the same name/port as the outside.
                    - fcrepo.${DOMAIN}
                    - ${DOMAIN}
        depends_on:
            # Sometimes traefik doesn't pick up on new containers so make sure they are started before traefik.
            - activemq
            - blazegraph
            - drupal
            - fcrepo
            - solr
