name: _bake

on:
  workflow_call:
    secrets:
      REGISTRY_USER:
        required: true
      REGISTRY_PASSWORD:
        required: true

jobs:
  bake:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          use: true
          driver-opts: |
            image=moby/buildkit:v0.11.1
            network=host
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - id: build
        name: Build and push
        run: |
          set -ex
          source .env
          export TAG=${{ github.ref_name }}
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg "REPOSITORY=${ISLANDORA_REPOSITORY}" \
            --build-arg "TAG=${ISLANDORA_TAG}" \
            --cache-to type=inline \
            --cache-from ${REPOSITORY}/sandbox:main \
            --cache-from ${REPOSITORY}/sandbox:${TAG}\
            --output "type=image,push=true" \
            --tag ${REPOSITORY}/sandbox:${TAG} drupal
