name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, closed]

concurrency:
  group: ${{ github.event.action == 'closed' && 'deploy-cleanup' || 'deploy' }}
  cancel-in-progress: ${{ github.event.action != 'closed' }}

jobs:
  test:
    name: Deploy to test.islandora.ca
    if: github.event.action != 'closed'
    uses: ./.github/workflows/create.yml
    secrets: inherit
    with:
      environment: test
      environment_url: https://test.islandora.ca

  sandbox:
    name: Deploy to sandbox.islandora.ca
    needs: [test]
    if: github.event_name == 'push'
    uses: ./.github/workflows/create.yml
    secrets: inherit
    with:
      environment: sandbox
      environment_url: https://sandbox.islandora.ca

  cleanup:
    name: Destroy test.islandora.ca
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment:
      name: test
      url: https://test.islandora.ca
    steps:
      - name: Set up doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
      - name: Get droplet ID
        id: get_droplet
        run: |
          name="test"
          droplet_id=$(doctl compute droplet list --format ID,Name --no-header | grep " ${name}\$" | awk '{print $1}')
          echo "droplet_id=$droplet_id" >> $GITHUB_OUTPUT
      - name: Destroy droplet
        if: ${{ steps.get_droplet.outputs.droplet_id != '' }}
        run: |
          droplet_id="${{ steps.get_droplet.outputs.droplet_id }}"
          doctl compute droplet delete "$droplet_id" --force
