name: Package Release

on:
  release:
    types: [created]

jobs:
  package:
    name: Package Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Remove build from docker-compose.yml
        uses: mikefarah/yq@v4.33.3
        with:
          cmd: yq -i 'del(.services.drupal.build)' docker-compose.yml
      - name: Create zip
        run: |
          TAG=${{ github.event.release.tag_name }} docker compose config > package/docker-compose.yml
          mv package islandora-sandbox-${{ github.event.release.tag_name }}
          zip -r islandora-sandbox.${{ github.event.release.tag_name }}.zip islandora-sandbox-${{ github.event.release.tag_name }}/*
      - name: Attach zip to Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Islandora Sandbox ${{ github.event.release.tag_name }}"
          files: islandora-sandbox.${{ github.event.release.tag_name }}.zip
          tag_name: ${{ github.event.release.tag_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
