name: push

on:
  push:
    branches:
      - "main"
      - "camp"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  bake:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:v0.11.1
            network=host
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.registry_user }}
          password: ${{ secrets.registry_password }}
      - name: Set TAG Environment Variable
        run: |
          echo "TAG=$GITHUB_REF_NAME" >> $GITHUB_ENV
      - id: build
        name: Build and push
        run: |
          set -ex
          make push manifest "BUILDER=${{ steps.buildx.outputs.name }}" "TARGET=ci" "TAG=${TAG}"
