name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  promote:
    name: Promote Sandbox
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_version: 1.14.6

      - name: Deploy and validate test
        run: make tf-test ACTION=apply
        env:
          ISLE_PASSWORD: ${{ secrets.ISLE_PASSWORD }}

      - name: Deploy and validate sandbox
        run: make tf-prod ACTION=apply
        env:
          ISLE_PASSWORD: ${{ secrets.ISLE_PASSWORD }}

      - name: Clean up test compute after sandbox promotion
        run: make tf-test ACTION=cleanup
        env:
          ISLE_PASSWORD: ${{ secrets.ISLE_PASSWORD }}

      - name: Dump logs on failure
        if: failure()
        env:
          PACKER_SSH_KEY: ${{ secrets.PACKER_SSH_KEY }}
        run: make dump-logs-prod
